
/*
 * This code was generated by Spiral 8.5.1, www.spiral.net
 */

#include <stdint.h>

void init_nttmpcuda() {
    /* skip */
}

__global__ void ker_code0(uint64_t  *X, uint64_t  *Y, uint64_t *modulus, uint64_t  *twiddles, uint64_t *mu) {
    int a1935, a1936, a1937, a1938, a1939, a1960, a1961, a1962, 
            a1963, a1964, a1965, a1966, a1967, a1968, a1969, a1971, 
            a1972, a1973, a1975, a1976, a1977, a1978, a1979, a1980, 
            a1981, a1982, a1983, a1984, a1985, a1986, a2005, a2006, 
            a2007, a2008, a2009, a2010, a2011, a2012, a2013, a2015, 
            a2016, a2018, a2019, a2020, a2021, a2022, a2023, a2024, 
            a2025, a2026, a2027, a2028, a2029, a2048, a2049, a2050, 
            a2051, a2052, a2053, a2054, a2055, a2056, a2058, a2059, 
            a2061, a2062, a2063, a2064, a2065, a2066, a2067, a2068, 
            a2069, a2070, a2071, a2072, a2091, a2092, a2093, a2094, 
            a2095, a2096, a2097, a2098, a2099, a2101, a2102, a2104, 
            a2105, a2106, a2107, a2108, a2109, a2110, a2111, a2112, 
            a2113, a2114, a2115, a2134, a2135, a2136, a2137, a2138, 
            a2139, a2140, a2141, a2142, a2144, a2145, a2147, a2148, 
            a2149, a2150, a2151, a2152, a2153, a2154, a2155, a2156, 
            a2157, a2158, a2177, a2178, a2179, a2180, a2181, a2182, 
            a2183, a2184, a2185, a2187, a2188, a2190, a2191, a2192, 
            a2193, a2194, a2195, a2196, a2197, a2198, a2199, a2200, 
            a2201, a2220, a2221, a2222, a2223, a2224, a2225, a2226, 
            a2227, a2228, a2230, a2231, a2233, a2234, a2235, a2236, 
            a2237, a2238, a2239, a2240, a2241, a2242, a2243, a2244, 
            a2263, a2264, a2265, a2266, a2267, a2268, a2269, a2270, 
            a2271, a2273, a2274, a2276, a2277, a2278, a2279, a2280, 
            a2281, a2282, a2283, a2284, a2285, a2286, a2287, a2306, 
            a2307, a2308, a2309, a2310, a2311, a2312, a2313, a2314, 
            a2316, a2317, a2319, a2320, a2321, a2322, a2323, a2324, 
            a2325, a2326, a2327, a2328, a2329, a2330, a2349, a2350, 
            a2351, a2352, a2353, a2354, a2355, a2356, a2357, a2358, 
            a2360, a2361, a2362, a2364, a2365, a2366, a2367, a2368, 
            b44, b45, b46, b47, b48, b49, b50, b51, 
            b52, b53, b54, b55, b56, b57, b58, b59, 
            b60, b61, b62, b63, b64, b65, b66, b67, 
            b68, b69, b70, b71, b72, b73, b74, b75, 
            b76, b77, b78, b79, b80, b81, b82, b83, 
            c119, c120, c129, c130, c139, c140, c149, c150, 
            c159, c160, c169, c170, c179, c180, c189, c190, 
            c199, c200, c209, c210, i187, i188, i189, i190, 
            i191, i192, i193, i194, i195, i196, i197, i198, 
            i199, i200, i201, i202, i203, i204, i205, i206, 
            i207, i208, i209, i210, i211, i212, i213, i214, 
            i215, i216;
    uint64_t a1944, a1945, a1946, a1947, a1948, a1953, a1954, a1991, 
            a1992, a1993, a1998, a1999, a2034, a2035, a2036, a2041, 
            a2042, a2077, a2078, a2079, a2084, a2085, a2120, a2121, 
            a2122, a2127, a2128, a2163, a2164, a2165, a2170, a2171, 
            a2206, a2207, a2208, a2213, a2214, a2249, a2250, a2251, 
            a2256, a2257, a2292, a2293, a2294, a2299, a2300, a2335, 
            a2336, a2337, a2342, a2343, d121, d122, d123, d124, 
            d125, d126, d127, d128, d129, d130, d131, d132, 
            d133, d134, d135, d136, d137, d138, d139, d140, 
            d141, d142, d143, d144, d145, d146, d147, d148, 
            d149, d150, d151, d152, d153, d154, d155, d156, 
            d157, d158, d159, d160, d161, d162, d163, d164, 
            d165, d166, d167, d168, d169, d170, d171, d172, 
            d173, d174, d175, d176, d177, d178, d179, d180, 
            d181, d182, d183, d184, d185, d186, d187, d188, 
            d189, d190, d191, d192, d193, d194, d195, d196, 
            d197, d198, d199, d200, d201, d202, d203, d204, 
            d205, d206, d207, d208, d209, d210, d211, d212, 
            d213, d214, d215, d216, d217, d218, d219, d220, 
            d221, d222, d223, d224, d225, d226, d227, d228, 
            d229, d230, d231, d232, d233, d234, d235, d236, 
            d237, d238, d239, d240, m4, p21, p22, p23, 
            p24, p25, p26, p27, p28, p29, p30, p31, 
            p32, p33, p34, p35, p36, p37, p38, p39, 
            p40, t160, t161, t164, t165, t543, t544, t545, 
            t546, t547, t548, t549, t550, t551, t552, t553, 
            t554, t555, t556, t557, t558, t559, t560, t561, 
            t562, t563, t564, t565, t566, t567, t568, t569, 
            t570, t571, t572, t573, t574, t575, t576, t577, 
            t578, t579, t580, t581, t582, t583, t584, t585, 
            t586, t587, t588, t589, t590, t591, t592, t593, 
            t594, t595, t596, t597, t598, t599, t600, t601, 
            t602, t603, t604, t605, t606, t607, t608, t609, 
            t610, t611, t612, t613, t614, t615, t616, t617, 
            t618, t619, t620, t621, t622, t623, t624, t625, 
            t626, t627, t628, t629, t630, t631, t632, t633, 
            t634, t635, t636, t637, t638, t639, t640, t641, 
            t642, t643, t644, t645, t646, t647, t648, t649, 
            t650, t651, t652, t653, t654, t655, t656, t657, 
            t658, t659, t660, t661, t662, t663, t664, t665, 
            t666, t667, t668, t669, t670, t671, t672, t673, 
            t674, t675, t676, t677, t678, t679, t680, t681, 
            t682, t683, t684, t685, t686, t687, t688, t689, 
            t690, t691, t692, t693, t694, t695, t696, t697, 
            t698, t699, t700, t701, t702, t703, t704, t705, 
            t706, t707, t708, t709, t710, t711, t712, t713, 
            t714, t715, t716, t717, t718, t719, t720, t721, 
            t722, t723, t724, t725, t726, t727, t728, t729, 
            t730, t731, t732, t733, t734, t735, t736, t737, 
            t738, t739, t740, t741, t742, t743, t744, t745, 
            t746, t747, t748, t749, t750, t751, t752, t753, 
            t754, t755, t756, t757, t758, t759, t760, t761, 
            t762, t763, t764, t765, t766, t767, t768, t769, 
            t770, t771, t772;
    uint128_t a1940, a1941, a1942, a1943, a1949, a1950, a1951, a1952, 
            a1955, a1956, a1957, a1987, a1988, a1989, a1990, a1994, 
            a1995, a1996, a1997, a2000, a2001, a2002, a2030, a2031, 
            a2032, a2033, a2037, a2038, a2039, a2040, a2043, a2044, 
            a2045, a2073, a2074, a2075, a2076, a2080, a2081, a2082, 
            a2083, a2086, a2087, a2088, a2116, a2117, a2118, a2119, 
            a2123, a2124, a2125, a2126, a2129, a2130, a2131, a2159, 
            a2160, a2161, a2162, a2166, a2167, a2168, a2169, a2172, 
            a2173, a2174, a2202, a2203, a2204, a2205, a2209, a2210, 
            a2211, a2212, a2215, a2216, a2217, a2245, a2246, a2247, 
            a2248, a2252, a2253, a2254, a2255, a2258, a2259, a2260, 
            a2288, a2289, a2290, a2291, a2295, a2296, a2297, a2298, 
            a2301, a2302, a2303, a2331, a2332, a2333, a2334, a2338, 
            a2339, a2340, a2341, a2344, a2345, a2346, c111, c112, 
            c113, c114, c115, c116, c117, c118, c121, c122, 
            c123, c124, c125, c126, c127, c128, c131, c132, 
            c133, c134, c135, c136, c137, c138, c141, c142, 
            c143, c144, c145, c146, c147, c148, c151, c152, 
            c153, c154, c155, c156, c157, c158, c161, c162, 
            c163, c164, c165, c166, c167, c168, c171, c172, 
            c173, c174, c175, c176, c177, c178, c181, c182, 
            c183, c184, c185, c186, c187, c188, c191, c192, 
            c193, c194, c195, c196, c197, c198, c201, c202, 
            c203, c204, c205, c206, c207, c208, s191, s192, 
            s193, s194, s195, s196, s197, s198, s199, s200, 
            s201, s202, s203, s204, s205, s206, s207, s208, 
            s209, s210, s211, s212, s213, s214, s215, s216, 
            s217, s218, s219, s220, s221, s222, s223, s224, 
            s225, s226, s227, s228, s229, s230, s231, s232, 
            s233, s234, s235, s236, s237, s238, s239, s240, 
            s241, s242, s243, s244, s245, s246, s247, s248, 
            s249, s250;
    __shared__ uint64_t T1[2048];
    __shared__ uint64_t T2[2048];
    a1935 = (1024*blockIdx.x);
    a1936 = (a1935 + threadIdx.x);
    a1937 = (a1936 + 512);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a1938 = (2*a1937);
    a1939 = (a1938 + 1);
    a1940 = (((uint128_t ) twiddles[3])*((uint128_t ) X[a1939]));
    a1941 = (((uint128_t ) twiddles[3])*((uint128_t ) X[a1938]));
    a1942 = (((uint128_t ) twiddles[2])*((uint128_t ) X[a1939]));
    a1943 = (((uint128_t ) twiddles[2])*((uint128_t ) X[a1938]));
    c111 = (((uint128_t ) a1941) + ((uint128_t ) a1942));
    t543 = (a1940 >> 64);
    c112 = (((uint128_t ) c111) + ((uint128_t ) t543));
    t544 = (c112 >> 64);
    c113 = (((uint128_t ) a1943) + ((uint128_t ) t544));
    t545 = (c113 >> 64);
    t546 = ((uint64_t ) c113);
    t547 = ((uint64_t ) c112);
    t548 = ((uint64_t ) a1940);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p21 = (t547 >> 58);
    a1944 = ((uint64_t ) 1);
    a1945 = (a1944 << 58);
    m4 = (a1945 - 1);
    p22 = (((t545)&(m4)));
    a1946 = (p22 << 6);
    a1947 = (t546 >> 58);
    t549 = (((a1946)|(a1947)));
    a1948 = (t546 << 6);
    t550 = (((a1948)|(p21)));
    /* End of MPShiftRight3 */
    t160 = mu[0];
    t161 = mu[1];
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a1949 = (((uint128_t ) t550)*((uint128_t ) t161));
    a1950 = (((uint128_t ) t550)*((uint128_t ) t160));
    a1951 = (((uint128_t ) t549)*((uint128_t ) t161));
    a1952 = (((uint128_t ) t549)*((uint128_t ) t160));
    c114 = (((uint128_t ) a1950) + ((uint128_t ) a1951));
    t551 = (a1949 >> 64);
    c115 = (((uint128_t ) c114) + ((uint128_t ) t551));
    t552 = (c115 >> 64);
    c116 = (((uint128_t ) a1952) + ((uint128_t ) t552));
    t553 = (c116 >> 64);
    t554 = ((uint64_t ) c116);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t555 = (t553 >> 1);
    a1953 = (t553 << 63);
    a1954 = (t554 >> 1);
    t556 = (((a1953)|(a1954)));
    /* End of MPShiftRight2 */
    t164 = modulus[0];
    t165 = modulus[1];
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a1955 = (((uint128_t ) t556)*((uint128_t ) t165));
    a1956 = (((uint128_t ) t556)*((uint128_t ) t164));
    a1957 = (((uint128_t ) t555)*((uint128_t ) t165));
    c117 = (((uint128_t ) a1956) + ((uint128_t ) a1957));
    t557 = (a1955 >> 64);
    c118 = (((uint128_t ) c117) + ((uint128_t ) t557));
    t558 = ((uint64_t ) c118);
    t559 = ((uint64_t ) a1955);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d121 = (t548 - t559);
    b44 = ((t548 < t559));
    d122 = (t547 - t558);
    d123 = (d122 - b44);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d124 = (d121 - t165);
    b45 = ((d121 < t165));
    d125 = (d123 - t164);
    d126 = (d125 - b45);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a1960 = ((d123 < t164));
    a1961 = ((d123 == t164));
    a1962 = ((a1961) && (b45));
    i187 = ((a1960) || (a1962));
    t560 = ((i187) ? (d123) : (d126));
    t561 = ((i187) ? (d121) : (d124));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a1963 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a1964 = (2*a1936);
    a1965 = (a1964 + 1);
    s191 = (((uint128_t ) X[a1965]) + ((uint128_t ) t561));
    t562 = ((uint64_t ) s191);
    c119 = (s191 >> 64);
    s192 = (((uint128_t ) X[a1964]) + ((uint128_t ) t560));
    s193 = (((uint128_t ) s192) + ((uint128_t ) c119));
    t563 = ((uint64_t ) s193);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a1966 = ((t164 < t563));
    a1967 = ((t164 == t563));
    a1968 = ((t165 < t562));
    a1969 = ((a1967) && (a1968));
    i188 = ((a1966) || (a1969));
    /* Begin of MPSubDDD 64 */
    d127 = (t562 - t165);
    b46 = ((t562 < t165));
    d128 = (t563 - t164);
    d129 = (d128 - b46);
    /* End of MPSubDDD 64 */
    a1971 = (2*a1963);
    T1[a1971] = ((i188) ? (d129) : (t563));
    a1972 = (a1971 + 1);
    T1[a1972] = ((i188) ? (d127) : (t562));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    a1973 = (a1963 + 1);
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d130 = (X[a1965] - t561);
    b47 = ((X[a1965] < t561));
    d131 = (X[a1964] - t560);
    d132 = (d131 - b47);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s194 = (((uint128_t ) d130) + ((uint128_t ) t165));
    t564 = ((uint64_t ) s194);
    c120 = (s194 >> 64);
    s195 = (((uint128_t ) d132) + ((uint128_t ) t164));
    s196 = (((uint128_t ) s195) + ((uint128_t ) c120));
    t565 = ((uint64_t ) s196);
    /* MPLessThan 64 */
    a1975 = ((X[a1964] < t560));
    a1976 = ((X[a1964] == t560));
    a1977 = ((a1976) && (b47));
    i189 = ((a1975) || (a1977));
    a1978 = (2*a1973);
    T1[a1978] = ((i189) ? (t565) : (d132));
    a1979 = (a1978 + 1);
    T1[a1979] = ((i189) ? (t564) : (d130));
    /* End of MPModSub 64 */
    __syncthreads();
    a1980 = (threadIdx.x + 512);
    a1981 = (a1980 % 2);
    a1982 = (2 + a1981);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a1983 = (2*a1982);
    a1984 = (a1983 + 1);
    a1985 = (2*a1980);
    a1986 = (a1985 + 1);
    a1987 = (((uint128_t ) twiddles[a1984])*((uint128_t ) T1[a1986]));
    a1988 = (((uint128_t ) twiddles[a1984])*((uint128_t ) T1[a1985]));
    a1989 = (((uint128_t ) twiddles[a1983])*((uint128_t ) T1[a1986]));
    a1990 = (((uint128_t ) twiddles[a1983])*((uint128_t ) T1[a1985]));
    c121 = (((uint128_t ) a1988) + ((uint128_t ) a1989));
    t566 = (a1987 >> 64);
    c122 = (((uint128_t ) c121) + ((uint128_t ) t566));
    t567 = (c122 >> 64);
    c123 = (((uint128_t ) a1990) + ((uint128_t ) t567));
    t568 = (c123 >> 64);
    t569 = ((uint64_t ) c123);
    t570 = ((uint64_t ) c122);
    t571 = ((uint64_t ) a1987);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p23 = (t570 >> 58);
    p24 = (((t568)&(m4)));
    a1991 = (p24 << 6);
    a1992 = (t569 >> 58);
    t572 = (((a1991)|(a1992)));
    a1993 = (t569 << 6);
    t573 = (((a1993)|(p23)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a1994 = (((uint128_t ) t573)*((uint128_t ) t161));
    a1995 = (((uint128_t ) t573)*((uint128_t ) t160));
    a1996 = (((uint128_t ) t572)*((uint128_t ) t161));
    a1997 = (((uint128_t ) t572)*((uint128_t ) t160));
    c124 = (((uint128_t ) a1995) + ((uint128_t ) a1996));
    t574 = (a1994 >> 64);
    c125 = (((uint128_t ) c124) + ((uint128_t ) t574));
    t575 = (c125 >> 64);
    c126 = (((uint128_t ) a1997) + ((uint128_t ) t575));
    t576 = (c126 >> 64);
    t577 = ((uint64_t ) c126);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t578 = (t576 >> 1);
    a1998 = (t576 << 63);
    a1999 = (t577 >> 1);
    t579 = (((a1998)|(a1999)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2000 = (((uint128_t ) t579)*((uint128_t ) t165));
    a2001 = (((uint128_t ) t579)*((uint128_t ) t164));
    a2002 = (((uint128_t ) t578)*((uint128_t ) t165));
    c127 = (((uint128_t ) a2001) + ((uint128_t ) a2002));
    t580 = (a2000 >> 64);
    c128 = (((uint128_t ) c127) + ((uint128_t ) t580));
    t581 = ((uint64_t ) c128);
    t582 = ((uint64_t ) a2000);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d133 = (t571 - t582);
    b48 = ((t571 < t582));
    d134 = (t570 - t581);
    d135 = (d134 - b48);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d136 = (d133 - t165);
    b49 = ((d133 < t165));
    d137 = (d135 - t164);
    d138 = (d137 - b49);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2005 = ((d135 < t164));
    a2006 = ((d135 == t164));
    a2007 = ((a2006) && (b49));
    i190 = ((a2005) || (a2007));
    t583 = ((i190) ? (d135) : (d138));
    t584 = ((i190) ? (d133) : (d136));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2008 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2009 = (a2008 + 1);
    s197 = (((uint128_t ) T1[a2009]) + ((uint128_t ) t584));
    t585 = ((uint64_t ) s197);
    c129 = (s197 >> 64);
    s198 = (((uint128_t ) T1[a2008]) + ((uint128_t ) t583));
    s199 = (((uint128_t ) s198) + ((uint128_t ) c129));
    t586 = ((uint64_t ) s199);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2010 = ((t164 < t586));
    a2011 = ((t164 == t586));
    a2012 = ((t165 < t585));
    a2013 = ((a2011) && (a2012));
    i191 = ((a2010) || (a2013));
    /* Begin of MPSubDDD 64 */
    d139 = (t585 - t165);
    b50 = ((t585 < t165));
    d140 = (t586 - t164);
    d141 = (d140 - b50);
    /* End of MPSubDDD 64 */
    a2015 = (2*a2008);
    T2[a2015] = ((i191) ? (d141) : (t586));
    a2016 = (a2015 + 1);
    T2[a2016] = ((i191) ? (d139) : (t585));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d142 = (T1[a2009] - t584);
    b51 = ((T1[a2009] < t584));
    d143 = (T1[a2008] - t583);
    d144 = (d143 - b51);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s200 = (((uint128_t ) d142) + ((uint128_t ) t165));
    t587 = ((uint64_t ) s200);
    c130 = (s200 >> 64);
    s201 = (((uint128_t ) d144) + ((uint128_t ) t164));
    s202 = (((uint128_t ) s201) + ((uint128_t ) c130));
    t588 = ((uint64_t ) s202);
    /* MPLessThan 64 */
    a2018 = ((T1[a2008] < t583));
    a2019 = ((T1[a2008] == t583));
    a2020 = ((a2019) && (b51));
    i192 = ((a2018) || (a2020));
    a2021 = (2*a2009);
    T2[a2021] = ((i192) ? (t588) : (d144));
    a2022 = (a2021 + 1);
    T2[a2022] = ((i192) ? (t587) : (d142));
    /* End of MPModSub 64 */
    __syncthreads();
    a2023 = (threadIdx.x + 512);
    a2024 = (a2023 % 4);
    a2025 = (4 + a2024);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2026 = (2*a2025);
    a2027 = (a2026 + 1);
    a2028 = (2*a2023);
    a2029 = (a2028 + 1);
    a2030 = (((uint128_t ) twiddles[a2027])*((uint128_t ) T2[a2029]));
    a2031 = (((uint128_t ) twiddles[a2027])*((uint128_t ) T2[a2028]));
    a2032 = (((uint128_t ) twiddles[a2026])*((uint128_t ) T2[a2029]));
    a2033 = (((uint128_t ) twiddles[a2026])*((uint128_t ) T2[a2028]));
    c131 = (((uint128_t ) a2031) + ((uint128_t ) a2032));
    t589 = (a2030 >> 64);
    c132 = (((uint128_t ) c131) + ((uint128_t ) t589));
    t590 = (c132 >> 64);
    c133 = (((uint128_t ) a2033) + ((uint128_t ) t590));
    t591 = (c133 >> 64);
    t592 = ((uint64_t ) c133);
    t593 = ((uint64_t ) c132);
    t594 = ((uint64_t ) a2030);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p25 = (t593 >> 58);
    p26 = (((t591)&(m4)));
    a2034 = (p26 << 6);
    a2035 = (t592 >> 58);
    t595 = (((a2034)|(a2035)));
    a2036 = (t592 << 6);
    t596 = (((a2036)|(p25)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2037 = (((uint128_t ) t596)*((uint128_t ) t161));
    a2038 = (((uint128_t ) t596)*((uint128_t ) t160));
    a2039 = (((uint128_t ) t595)*((uint128_t ) t161));
    a2040 = (((uint128_t ) t595)*((uint128_t ) t160));
    c134 = (((uint128_t ) a2038) + ((uint128_t ) a2039));
    t597 = (a2037 >> 64);
    c135 = (((uint128_t ) c134) + ((uint128_t ) t597));
    t598 = (c135 >> 64);
    c136 = (((uint128_t ) a2040) + ((uint128_t ) t598));
    t599 = (c136 >> 64);
    t600 = ((uint64_t ) c136);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t601 = (t599 >> 1);
    a2041 = (t599 << 63);
    a2042 = (t600 >> 1);
    t602 = (((a2041)|(a2042)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2043 = (((uint128_t ) t602)*((uint128_t ) t165));
    a2044 = (((uint128_t ) t602)*((uint128_t ) t164));
    a2045 = (((uint128_t ) t601)*((uint128_t ) t165));
    c137 = (((uint128_t ) a2044) + ((uint128_t ) a2045));
    t603 = (a2043 >> 64);
    c138 = (((uint128_t ) c137) + ((uint128_t ) t603));
    t604 = ((uint64_t ) c138);
    t605 = ((uint64_t ) a2043);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d145 = (t594 - t605);
    b52 = ((t594 < t605));
    d146 = (t593 - t604);
    d147 = (d146 - b52);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d148 = (d145 - t165);
    b53 = ((d145 < t165));
    d149 = (d147 - t164);
    d150 = (d149 - b53);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2048 = ((d147 < t164));
    a2049 = ((d147 == t164));
    a2050 = ((a2049) && (b53));
    i193 = ((a2048) || (a2050));
    t606 = ((i193) ? (d147) : (d150));
    t607 = ((i193) ? (d145) : (d148));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2051 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2052 = (a2051 + 1);
    s203 = (((uint128_t ) T2[a2052]) + ((uint128_t ) t607));
    t608 = ((uint64_t ) s203);
    c139 = (s203 >> 64);
    s204 = (((uint128_t ) T2[a2051]) + ((uint128_t ) t606));
    s205 = (((uint128_t ) s204) + ((uint128_t ) c139));
    t609 = ((uint64_t ) s205);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2053 = ((t164 < t609));
    a2054 = ((t164 == t609));
    a2055 = ((t165 < t608));
    a2056 = ((a2054) && (a2055));
    i194 = ((a2053) || (a2056));
    /* Begin of MPSubDDD 64 */
    d151 = (t608 - t165);
    b54 = ((t608 < t165));
    d152 = (t609 - t164);
    d153 = (d152 - b54);
    /* End of MPSubDDD 64 */
    a2058 = (2*a2051);
    T1[a2058] = ((i194) ? (d153) : (t609));
    a2059 = (a2058 + 1);
    T1[a2059] = ((i194) ? (d151) : (t608));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d154 = (T2[a2052] - t607);
    b55 = ((T2[a2052] < t607));
    d155 = (T2[a2051] - t606);
    d156 = (d155 - b55);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s206 = (((uint128_t ) d154) + ((uint128_t ) t165));
    t610 = ((uint64_t ) s206);
    c140 = (s206 >> 64);
    s207 = (((uint128_t ) d156) + ((uint128_t ) t164));
    s208 = (((uint128_t ) s207) + ((uint128_t ) c140));
    t611 = ((uint64_t ) s208);
    /* MPLessThan 64 */
    a2061 = ((T2[a2051] < t606));
    a2062 = ((T2[a2051] == t606));
    a2063 = ((a2062) && (b55));
    i195 = ((a2061) || (a2063));
    a2064 = (2*a2052);
    T1[a2064] = ((i195) ? (t611) : (d156));
    a2065 = (a2064 + 1);
    T1[a2065] = ((i195) ? (t610) : (d154));
    /* End of MPModSub 64 */
    __syncthreads();
    a2066 = (threadIdx.x + 512);
    a2067 = (a2066 % 8);
    a2068 = (8 + a2067);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2069 = (2*a2068);
    a2070 = (a2069 + 1);
    a2071 = (2*a2066);
    a2072 = (a2071 + 1);
    a2073 = (((uint128_t ) twiddles[a2070])*((uint128_t ) T1[a2072]));
    a2074 = (((uint128_t ) twiddles[a2070])*((uint128_t ) T1[a2071]));
    a2075 = (((uint128_t ) twiddles[a2069])*((uint128_t ) T1[a2072]));
    a2076 = (((uint128_t ) twiddles[a2069])*((uint128_t ) T1[a2071]));
    c141 = (((uint128_t ) a2074) + ((uint128_t ) a2075));
    t612 = (a2073 >> 64);
    c142 = (((uint128_t ) c141) + ((uint128_t ) t612));
    t613 = (c142 >> 64);
    c143 = (((uint128_t ) a2076) + ((uint128_t ) t613));
    t614 = (c143 >> 64);
    t615 = ((uint64_t ) c143);
    t616 = ((uint64_t ) c142);
    t617 = ((uint64_t ) a2073);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p27 = (t616 >> 58);
    p28 = (((t614)&(m4)));
    a2077 = (p28 << 6);
    a2078 = (t615 >> 58);
    t618 = (((a2077)|(a2078)));
    a2079 = (t615 << 6);
    t619 = (((a2079)|(p27)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2080 = (((uint128_t ) t619)*((uint128_t ) t161));
    a2081 = (((uint128_t ) t619)*((uint128_t ) t160));
    a2082 = (((uint128_t ) t618)*((uint128_t ) t161));
    a2083 = (((uint128_t ) t618)*((uint128_t ) t160));
    c144 = (((uint128_t ) a2081) + ((uint128_t ) a2082));
    t620 = (a2080 >> 64);
    c145 = (((uint128_t ) c144) + ((uint128_t ) t620));
    t621 = (c145 >> 64);
    c146 = (((uint128_t ) a2083) + ((uint128_t ) t621));
    t622 = (c146 >> 64);
    t623 = ((uint64_t ) c146);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t624 = (t622 >> 1);
    a2084 = (t622 << 63);
    a2085 = (t623 >> 1);
    t625 = (((a2084)|(a2085)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2086 = (((uint128_t ) t625)*((uint128_t ) t165));
    a2087 = (((uint128_t ) t625)*((uint128_t ) t164));
    a2088 = (((uint128_t ) t624)*((uint128_t ) t165));
    c147 = (((uint128_t ) a2087) + ((uint128_t ) a2088));
    t626 = (a2086 >> 64);
    c148 = (((uint128_t ) c147) + ((uint128_t ) t626));
    t627 = ((uint64_t ) c148);
    t628 = ((uint64_t ) a2086);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d157 = (t617 - t628);
    b56 = ((t617 < t628));
    d158 = (t616 - t627);
    d159 = (d158 - b56);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d160 = (d157 - t165);
    b57 = ((d157 < t165));
    d161 = (d159 - t164);
    d162 = (d161 - b57);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2091 = ((d159 < t164));
    a2092 = ((d159 == t164));
    a2093 = ((a2092) && (b57));
    i196 = ((a2091) || (a2093));
    t629 = ((i196) ? (d159) : (d162));
    t630 = ((i196) ? (d157) : (d160));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2094 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2095 = (a2094 + 1);
    s209 = (((uint128_t ) T1[a2095]) + ((uint128_t ) t630));
    t631 = ((uint64_t ) s209);
    c149 = (s209 >> 64);
    s210 = (((uint128_t ) T1[a2094]) + ((uint128_t ) t629));
    s211 = (((uint128_t ) s210) + ((uint128_t ) c149));
    t632 = ((uint64_t ) s211);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2096 = ((t164 < t632));
    a2097 = ((t164 == t632));
    a2098 = ((t165 < t631));
    a2099 = ((a2097) && (a2098));
    i197 = ((a2096) || (a2099));
    /* Begin of MPSubDDD 64 */
    d163 = (t631 - t165);
    b58 = ((t631 < t165));
    d164 = (t632 - t164);
    d165 = (d164 - b58);
    /* End of MPSubDDD 64 */
    a2101 = (2*a2094);
    T2[a2101] = ((i197) ? (d165) : (t632));
    a2102 = (a2101 + 1);
    T2[a2102] = ((i197) ? (d163) : (t631));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d166 = (T1[a2095] - t630);
    b59 = ((T1[a2095] < t630));
    d167 = (T1[a2094] - t629);
    d168 = (d167 - b59);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s212 = (((uint128_t ) d166) + ((uint128_t ) t165));
    t633 = ((uint64_t ) s212);
    c150 = (s212 >> 64);
    s213 = (((uint128_t ) d168) + ((uint128_t ) t164));
    s214 = (((uint128_t ) s213) + ((uint128_t ) c150));
    t634 = ((uint64_t ) s214);
    /* MPLessThan 64 */
    a2104 = ((T1[a2094] < t629));
    a2105 = ((T1[a2094] == t629));
    a2106 = ((a2105) && (b59));
    i198 = ((a2104) || (a2106));
    a2107 = (2*a2095);
    T2[a2107] = ((i198) ? (t634) : (d168));
    a2108 = (a2107 + 1);
    T2[a2108] = ((i198) ? (t633) : (d166));
    /* End of MPModSub 64 */
    __syncthreads();
    a2109 = (threadIdx.x + 512);
    a2110 = (a2109 % 16);
    a2111 = (16 + a2110);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2112 = (2*a2111);
    a2113 = (a2112 + 1);
    a2114 = (2*a2109);
    a2115 = (a2114 + 1);
    a2116 = (((uint128_t ) twiddles[a2113])*((uint128_t ) T2[a2115]));
    a2117 = (((uint128_t ) twiddles[a2113])*((uint128_t ) T2[a2114]));
    a2118 = (((uint128_t ) twiddles[a2112])*((uint128_t ) T2[a2115]));
    a2119 = (((uint128_t ) twiddles[a2112])*((uint128_t ) T2[a2114]));
    c151 = (((uint128_t ) a2117) + ((uint128_t ) a2118));
    t635 = (a2116 >> 64);
    c152 = (((uint128_t ) c151) + ((uint128_t ) t635));
    t636 = (c152 >> 64);
    c153 = (((uint128_t ) a2119) + ((uint128_t ) t636));
    t637 = (c153 >> 64);
    t638 = ((uint64_t ) c153);
    t639 = ((uint64_t ) c152);
    t640 = ((uint64_t ) a2116);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p29 = (t639 >> 58);
    p30 = (((t637)&(m4)));
    a2120 = (p30 << 6);
    a2121 = (t638 >> 58);
    t641 = (((a2120)|(a2121)));
    a2122 = (t638 << 6);
    t642 = (((a2122)|(p29)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2123 = (((uint128_t ) t642)*((uint128_t ) t161));
    a2124 = (((uint128_t ) t642)*((uint128_t ) t160));
    a2125 = (((uint128_t ) t641)*((uint128_t ) t161));
    a2126 = (((uint128_t ) t641)*((uint128_t ) t160));
    c154 = (((uint128_t ) a2124) + ((uint128_t ) a2125));
    t643 = (a2123 >> 64);
    c155 = (((uint128_t ) c154) + ((uint128_t ) t643));
    t644 = (c155 >> 64);
    c156 = (((uint128_t ) a2126) + ((uint128_t ) t644));
    t645 = (c156 >> 64);
    t646 = ((uint64_t ) c156);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t647 = (t645 >> 1);
    a2127 = (t645 << 63);
    a2128 = (t646 >> 1);
    t648 = (((a2127)|(a2128)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2129 = (((uint128_t ) t648)*((uint128_t ) t165));
    a2130 = (((uint128_t ) t648)*((uint128_t ) t164));
    a2131 = (((uint128_t ) t647)*((uint128_t ) t165));
    c157 = (((uint128_t ) a2130) + ((uint128_t ) a2131));
    t649 = (a2129 >> 64);
    c158 = (((uint128_t ) c157) + ((uint128_t ) t649));
    t650 = ((uint64_t ) c158);
    t651 = ((uint64_t ) a2129);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d169 = (t640 - t651);
    b60 = ((t640 < t651));
    d170 = (t639 - t650);
    d171 = (d170 - b60);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d172 = (d169 - t165);
    b61 = ((d169 < t165));
    d173 = (d171 - t164);
    d174 = (d173 - b61);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2134 = ((d171 < t164));
    a2135 = ((d171 == t164));
    a2136 = ((a2135) && (b61));
    i199 = ((a2134) || (a2136));
    t652 = ((i199) ? (d171) : (d174));
    t653 = ((i199) ? (d169) : (d172));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2137 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2138 = (a2137 + 1);
    s215 = (((uint128_t ) T2[a2138]) + ((uint128_t ) t653));
    t654 = ((uint64_t ) s215);
    c159 = (s215 >> 64);
    s216 = (((uint128_t ) T2[a2137]) + ((uint128_t ) t652));
    s217 = (((uint128_t ) s216) + ((uint128_t ) c159));
    t655 = ((uint64_t ) s217);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2139 = ((t164 < t655));
    a2140 = ((t164 == t655));
    a2141 = ((t165 < t654));
    a2142 = ((a2140) && (a2141));
    i200 = ((a2139) || (a2142));
    /* Begin of MPSubDDD 64 */
    d175 = (t654 - t165);
    b62 = ((t654 < t165));
    d176 = (t655 - t164);
    d177 = (d176 - b62);
    /* End of MPSubDDD 64 */
    a2144 = (2*a2137);
    T1[a2144] = ((i200) ? (d177) : (t655));
    a2145 = (a2144 + 1);
    T1[a2145] = ((i200) ? (d175) : (t654));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d178 = (T2[a2138] - t653);
    b63 = ((T2[a2138] < t653));
    d179 = (T2[a2137] - t652);
    d180 = (d179 - b63);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s218 = (((uint128_t ) d178) + ((uint128_t ) t165));
    t656 = ((uint64_t ) s218);
    c160 = (s218 >> 64);
    s219 = (((uint128_t ) d180) + ((uint128_t ) t164));
    s220 = (((uint128_t ) s219) + ((uint128_t ) c160));
    t657 = ((uint64_t ) s220);
    /* MPLessThan 64 */
    a2147 = ((T2[a2137] < t652));
    a2148 = ((T2[a2137] == t652));
    a2149 = ((a2148) && (b63));
    i201 = ((a2147) || (a2149));
    a2150 = (2*a2138);
    T1[a2150] = ((i201) ? (t657) : (d180));
    a2151 = (a2150 + 1);
    T1[a2151] = ((i201) ? (t656) : (d178));
    /* End of MPModSub 64 */
    __syncthreads();
    a2152 = (threadIdx.x + 512);
    a2153 = (a2152 % 32);
    a2154 = (32 + a2153);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2155 = (2*a2154);
    a2156 = (a2155 + 1);
    a2157 = (2*a2152);
    a2158 = (a2157 + 1);
    a2159 = (((uint128_t ) twiddles[a2156])*((uint128_t ) T1[a2158]));
    a2160 = (((uint128_t ) twiddles[a2156])*((uint128_t ) T1[a2157]));
    a2161 = (((uint128_t ) twiddles[a2155])*((uint128_t ) T1[a2158]));
    a2162 = (((uint128_t ) twiddles[a2155])*((uint128_t ) T1[a2157]));
    c161 = (((uint128_t ) a2160) + ((uint128_t ) a2161));
    t658 = (a2159 >> 64);
    c162 = (((uint128_t ) c161) + ((uint128_t ) t658));
    t659 = (c162 >> 64);
    c163 = (((uint128_t ) a2162) + ((uint128_t ) t659));
    t660 = (c163 >> 64);
    t661 = ((uint64_t ) c163);
    t662 = ((uint64_t ) c162);
    t663 = ((uint64_t ) a2159);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p31 = (t662 >> 58);
    p32 = (((t660)&(m4)));
    a2163 = (p32 << 6);
    a2164 = (t661 >> 58);
    t664 = (((a2163)|(a2164)));
    a2165 = (t661 << 6);
    t665 = (((a2165)|(p31)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2166 = (((uint128_t ) t665)*((uint128_t ) t161));
    a2167 = (((uint128_t ) t665)*((uint128_t ) t160));
    a2168 = (((uint128_t ) t664)*((uint128_t ) t161));
    a2169 = (((uint128_t ) t664)*((uint128_t ) t160));
    c164 = (((uint128_t ) a2167) + ((uint128_t ) a2168));
    t666 = (a2166 >> 64);
    c165 = (((uint128_t ) c164) + ((uint128_t ) t666));
    t667 = (c165 >> 64);
    c166 = (((uint128_t ) a2169) + ((uint128_t ) t667));
    t668 = (c166 >> 64);
    t669 = ((uint64_t ) c166);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t670 = (t668 >> 1);
    a2170 = (t668 << 63);
    a2171 = (t669 >> 1);
    t671 = (((a2170)|(a2171)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2172 = (((uint128_t ) t671)*((uint128_t ) t165));
    a2173 = (((uint128_t ) t671)*((uint128_t ) t164));
    a2174 = (((uint128_t ) t670)*((uint128_t ) t165));
    c167 = (((uint128_t ) a2173) + ((uint128_t ) a2174));
    t672 = (a2172 >> 64);
    c168 = (((uint128_t ) c167) + ((uint128_t ) t672));
    t673 = ((uint64_t ) c168);
    t674 = ((uint64_t ) a2172);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d181 = (t663 - t674);
    b64 = ((t663 < t674));
    d182 = (t662 - t673);
    d183 = (d182 - b64);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d184 = (d181 - t165);
    b65 = ((d181 < t165));
    d185 = (d183 - t164);
    d186 = (d185 - b65);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2177 = ((d183 < t164));
    a2178 = ((d183 == t164));
    a2179 = ((a2178) && (b65));
    i202 = ((a2177) || (a2179));
    t675 = ((i202) ? (d183) : (d186));
    t676 = ((i202) ? (d181) : (d184));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2180 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2181 = (a2180 + 1);
    s221 = (((uint128_t ) T1[a2181]) + ((uint128_t ) t676));
    t677 = ((uint64_t ) s221);
    c169 = (s221 >> 64);
    s222 = (((uint128_t ) T1[a2180]) + ((uint128_t ) t675));
    s223 = (((uint128_t ) s222) + ((uint128_t ) c169));
    t678 = ((uint64_t ) s223);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2182 = ((t164 < t678));
    a2183 = ((t164 == t678));
    a2184 = ((t165 < t677));
    a2185 = ((a2183) && (a2184));
    i203 = ((a2182) || (a2185));
    /* Begin of MPSubDDD 64 */
    d187 = (t677 - t165);
    b66 = ((t677 < t165));
    d188 = (t678 - t164);
    d189 = (d188 - b66);
    /* End of MPSubDDD 64 */
    a2187 = (2*a2180);
    T2[a2187] = ((i203) ? (d189) : (t678));
    a2188 = (a2187 + 1);
    T2[a2188] = ((i203) ? (d187) : (t677));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d190 = (T1[a2181] - t676);
    b67 = ((T1[a2181] < t676));
    d191 = (T1[a2180] - t675);
    d192 = (d191 - b67);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s224 = (((uint128_t ) d190) + ((uint128_t ) t165));
    t679 = ((uint64_t ) s224);
    c170 = (s224 >> 64);
    s225 = (((uint128_t ) d192) + ((uint128_t ) t164));
    s226 = (((uint128_t ) s225) + ((uint128_t ) c170));
    t680 = ((uint64_t ) s226);
    /* MPLessThan 64 */
    a2190 = ((T1[a2180] < t675));
    a2191 = ((T1[a2180] == t675));
    a2192 = ((a2191) && (b67));
    i204 = ((a2190) || (a2192));
    a2193 = (2*a2181);
    T2[a2193] = ((i204) ? (t680) : (d192));
    a2194 = (a2193 + 1);
    T2[a2194] = ((i204) ? (t679) : (d190));
    /* End of MPModSub 64 */
    __syncthreads();
    a2195 = (threadIdx.x + 512);
    a2196 = (a2195 % 64);
    a2197 = (64 + a2196);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2198 = (2*a2197);
    a2199 = (a2198 + 1);
    a2200 = (2*a2195);
    a2201 = (a2200 + 1);
    a2202 = (((uint128_t ) twiddles[a2199])*((uint128_t ) T2[a2201]));
    a2203 = (((uint128_t ) twiddles[a2199])*((uint128_t ) T2[a2200]));
    a2204 = (((uint128_t ) twiddles[a2198])*((uint128_t ) T2[a2201]));
    a2205 = (((uint128_t ) twiddles[a2198])*((uint128_t ) T2[a2200]));
    c171 = (((uint128_t ) a2203) + ((uint128_t ) a2204));
    t681 = (a2202 >> 64);
    c172 = (((uint128_t ) c171) + ((uint128_t ) t681));
    t682 = (c172 >> 64);
    c173 = (((uint128_t ) a2205) + ((uint128_t ) t682));
    t683 = (c173 >> 64);
    t684 = ((uint64_t ) c173);
    t685 = ((uint64_t ) c172);
    t686 = ((uint64_t ) a2202);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p33 = (t685 >> 58);
    p34 = (((t683)&(m4)));
    a2206 = (p34 << 6);
    a2207 = (t684 >> 58);
    t687 = (((a2206)|(a2207)));
    a2208 = (t684 << 6);
    t688 = (((a2208)|(p33)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2209 = (((uint128_t ) t688)*((uint128_t ) t161));
    a2210 = (((uint128_t ) t688)*((uint128_t ) t160));
    a2211 = (((uint128_t ) t687)*((uint128_t ) t161));
    a2212 = (((uint128_t ) t687)*((uint128_t ) t160));
    c174 = (((uint128_t ) a2210) + ((uint128_t ) a2211));
    t689 = (a2209 >> 64);
    c175 = (((uint128_t ) c174) + ((uint128_t ) t689));
    t690 = (c175 >> 64);
    c176 = (((uint128_t ) a2212) + ((uint128_t ) t690));
    t691 = (c176 >> 64);
    t692 = ((uint64_t ) c176);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t693 = (t691 >> 1);
    a2213 = (t691 << 63);
    a2214 = (t692 >> 1);
    t694 = (((a2213)|(a2214)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2215 = (((uint128_t ) t694)*((uint128_t ) t165));
    a2216 = (((uint128_t ) t694)*((uint128_t ) t164));
    a2217 = (((uint128_t ) t693)*((uint128_t ) t165));
    c177 = (((uint128_t ) a2216) + ((uint128_t ) a2217));
    t695 = (a2215 >> 64);
    c178 = (((uint128_t ) c177) + ((uint128_t ) t695));
    t696 = ((uint64_t ) c178);
    t697 = ((uint64_t ) a2215);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d193 = (t686 - t697);
    b68 = ((t686 < t697));
    d194 = (t685 - t696);
    d195 = (d194 - b68);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d196 = (d193 - t165);
    b69 = ((d193 < t165));
    d197 = (d195 - t164);
    d198 = (d197 - b69);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2220 = ((d195 < t164));
    a2221 = ((d195 == t164));
    a2222 = ((a2221) && (b69));
    i205 = ((a2220) || (a2222));
    t698 = ((i205) ? (d195) : (d198));
    t699 = ((i205) ? (d193) : (d196));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2223 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2224 = (a2223 + 1);
    s227 = (((uint128_t ) T2[a2224]) + ((uint128_t ) t699));
    t700 = ((uint64_t ) s227);
    c179 = (s227 >> 64);
    s228 = (((uint128_t ) T2[a2223]) + ((uint128_t ) t698));
    s229 = (((uint128_t ) s228) + ((uint128_t ) c179));
    t701 = ((uint64_t ) s229);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2225 = ((t164 < t701));
    a2226 = ((t164 == t701));
    a2227 = ((t165 < t700));
    a2228 = ((a2226) && (a2227));
    i206 = ((a2225) || (a2228));
    /* Begin of MPSubDDD 64 */
    d199 = (t700 - t165);
    b70 = ((t700 < t165));
    d200 = (t701 - t164);
    d201 = (d200 - b70);
    /* End of MPSubDDD 64 */
    a2230 = (2*a2223);
    T1[a2230] = ((i206) ? (d201) : (t701));
    a2231 = (a2230 + 1);
    T1[a2231] = ((i206) ? (d199) : (t700));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d202 = (T2[a2224] - t699);
    b71 = ((T2[a2224] < t699));
    d203 = (T2[a2223] - t698);
    d204 = (d203 - b71);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s230 = (((uint128_t ) d202) + ((uint128_t ) t165));
    t702 = ((uint64_t ) s230);
    c180 = (s230 >> 64);
    s231 = (((uint128_t ) d204) + ((uint128_t ) t164));
    s232 = (((uint128_t ) s231) + ((uint128_t ) c180));
    t703 = ((uint64_t ) s232);
    /* MPLessThan 64 */
    a2233 = ((T2[a2223] < t698));
    a2234 = ((T2[a2223] == t698));
    a2235 = ((a2234) && (b71));
    i207 = ((a2233) || (a2235));
    a2236 = (2*a2224);
    T1[a2236] = ((i207) ? (t703) : (d204));
    a2237 = (a2236 + 1);
    T1[a2237] = ((i207) ? (t702) : (d202));
    /* End of MPModSub 64 */
    __syncthreads();
    a2238 = (threadIdx.x + 512);
    a2239 = (a2238 % 128);
    a2240 = (128 + a2239);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2241 = (2*a2240);
    a2242 = (a2241 + 1);
    a2243 = (2*a2238);
    a2244 = (a2243 + 1);
    a2245 = (((uint128_t ) twiddles[a2242])*((uint128_t ) T1[a2244]));
    a2246 = (((uint128_t ) twiddles[a2242])*((uint128_t ) T1[a2243]));
    a2247 = (((uint128_t ) twiddles[a2241])*((uint128_t ) T1[a2244]));
    a2248 = (((uint128_t ) twiddles[a2241])*((uint128_t ) T1[a2243]));
    c181 = (((uint128_t ) a2246) + ((uint128_t ) a2247));
    t704 = (a2245 >> 64);
    c182 = (((uint128_t ) c181) + ((uint128_t ) t704));
    t705 = (c182 >> 64);
    c183 = (((uint128_t ) a2248) + ((uint128_t ) t705));
    t706 = (c183 >> 64);
    t707 = ((uint64_t ) c183);
    t708 = ((uint64_t ) c182);
    t709 = ((uint64_t ) a2245);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p35 = (t708 >> 58);
    p36 = (((t706)&(m4)));
    a2249 = (p36 << 6);
    a2250 = (t707 >> 58);
    t710 = (((a2249)|(a2250)));
    a2251 = (t707 << 6);
    t711 = (((a2251)|(p35)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2252 = (((uint128_t ) t711)*((uint128_t ) t161));
    a2253 = (((uint128_t ) t711)*((uint128_t ) t160));
    a2254 = (((uint128_t ) t710)*((uint128_t ) t161));
    a2255 = (((uint128_t ) t710)*((uint128_t ) t160));
    c184 = (((uint128_t ) a2253) + ((uint128_t ) a2254));
    t712 = (a2252 >> 64);
    c185 = (((uint128_t ) c184) + ((uint128_t ) t712));
    t713 = (c185 >> 64);
    c186 = (((uint128_t ) a2255) + ((uint128_t ) t713));
    t714 = (c186 >> 64);
    t715 = ((uint64_t ) c186);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t716 = (t714 >> 1);
    a2256 = (t714 << 63);
    a2257 = (t715 >> 1);
    t717 = (((a2256)|(a2257)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2258 = (((uint128_t ) t717)*((uint128_t ) t165));
    a2259 = (((uint128_t ) t717)*((uint128_t ) t164));
    a2260 = (((uint128_t ) t716)*((uint128_t ) t165));
    c187 = (((uint128_t ) a2259) + ((uint128_t ) a2260));
    t718 = (a2258 >> 64);
    c188 = (((uint128_t ) c187) + ((uint128_t ) t718));
    t719 = ((uint64_t ) c188);
    t720 = ((uint64_t ) a2258);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d205 = (t709 - t720);
    b72 = ((t709 < t720));
    d206 = (t708 - t719);
    d207 = (d206 - b72);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d208 = (d205 - t165);
    b73 = ((d205 < t165));
    d209 = (d207 - t164);
    d210 = (d209 - b73);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2263 = ((d207 < t164));
    a2264 = ((d207 == t164));
    a2265 = ((a2264) && (b73));
    i208 = ((a2263) || (a2265));
    t721 = ((i208) ? (d207) : (d210));
    t722 = ((i208) ? (d205) : (d208));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2266 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2267 = (a2266 + 1);
    s233 = (((uint128_t ) T1[a2267]) + ((uint128_t ) t722));
    t723 = ((uint64_t ) s233);
    c189 = (s233 >> 64);
    s234 = (((uint128_t ) T1[a2266]) + ((uint128_t ) t721));
    s235 = (((uint128_t ) s234) + ((uint128_t ) c189));
    t724 = ((uint64_t ) s235);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2268 = ((t164 < t724));
    a2269 = ((t164 == t724));
    a2270 = ((t165 < t723));
    a2271 = ((a2269) && (a2270));
    i209 = ((a2268) || (a2271));
    /* Begin of MPSubDDD 64 */
    d211 = (t723 - t165);
    b74 = ((t723 < t165));
    d212 = (t724 - t164);
    d213 = (d212 - b74);
    /* End of MPSubDDD 64 */
    a2273 = (2*a2266);
    T2[a2273] = ((i209) ? (d213) : (t724));
    a2274 = (a2273 + 1);
    T2[a2274] = ((i209) ? (d211) : (t723));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d214 = (T1[a2267] - t722);
    b75 = ((T1[a2267] < t722));
    d215 = (T1[a2266] - t721);
    d216 = (d215 - b75);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s236 = (((uint128_t ) d214) + ((uint128_t ) t165));
    t725 = ((uint64_t ) s236);
    c190 = (s236 >> 64);
    s237 = (((uint128_t ) d216) + ((uint128_t ) t164));
    s238 = (((uint128_t ) s237) + ((uint128_t ) c190));
    t726 = ((uint64_t ) s238);
    /* MPLessThan 64 */
    a2276 = ((T1[a2266] < t721));
    a2277 = ((T1[a2266] == t721));
    a2278 = ((a2277) && (b75));
    i210 = ((a2276) || (a2278));
    a2279 = (2*a2267);
    T2[a2279] = ((i210) ? (t726) : (d216));
    a2280 = (a2279 + 1);
    T2[a2280] = ((i210) ? (t725) : (d214));
    /* End of MPModSub 64 */
    __syncthreads();
    a2281 = (threadIdx.x + 512);
    a2282 = (a2281 % 256);
    a2283 = (256 + a2282);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2284 = (2*a2283);
    a2285 = (a2284 + 1);
    a2286 = (2*a2281);
    a2287 = (a2286 + 1);
    a2288 = (((uint128_t ) twiddles[a2285])*((uint128_t ) T2[a2287]));
    a2289 = (((uint128_t ) twiddles[a2285])*((uint128_t ) T2[a2286]));
    a2290 = (((uint128_t ) twiddles[a2284])*((uint128_t ) T2[a2287]));
    a2291 = (((uint128_t ) twiddles[a2284])*((uint128_t ) T2[a2286]));
    c191 = (((uint128_t ) a2289) + ((uint128_t ) a2290));
    t727 = (a2288 >> 64);
    c192 = (((uint128_t ) c191) + ((uint128_t ) t727));
    t728 = (c192 >> 64);
    c193 = (((uint128_t ) a2291) + ((uint128_t ) t728));
    t729 = (c193 >> 64);
    t730 = ((uint64_t ) c193);
    t731 = ((uint64_t ) c192);
    t732 = ((uint64_t ) a2288);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p37 = (t731 >> 58);
    p38 = (((t729)&(m4)));
    a2292 = (p38 << 6);
    a2293 = (t730 >> 58);
    t733 = (((a2292)|(a2293)));
    a2294 = (t730 << 6);
    t734 = (((a2294)|(p37)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2295 = (((uint128_t ) t734)*((uint128_t ) t161));
    a2296 = (((uint128_t ) t734)*((uint128_t ) t160));
    a2297 = (((uint128_t ) t733)*((uint128_t ) t161));
    a2298 = (((uint128_t ) t733)*((uint128_t ) t160));
    c194 = (((uint128_t ) a2296) + ((uint128_t ) a2297));
    t735 = (a2295 >> 64);
    c195 = (((uint128_t ) c194) + ((uint128_t ) t735));
    t736 = (c195 >> 64);
    c196 = (((uint128_t ) a2298) + ((uint128_t ) t736));
    t737 = (c196 >> 64);
    t738 = ((uint64_t ) c196);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t739 = (t737 >> 1);
    a2299 = (t737 << 63);
    a2300 = (t738 >> 1);
    t740 = (((a2299)|(a2300)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2301 = (((uint128_t ) t740)*((uint128_t ) t165));
    a2302 = (((uint128_t ) t740)*((uint128_t ) t164));
    a2303 = (((uint128_t ) t739)*((uint128_t ) t165));
    c197 = (((uint128_t ) a2302) + ((uint128_t ) a2303));
    t741 = (a2301 >> 64);
    c198 = (((uint128_t ) c197) + ((uint128_t ) t741));
    t742 = ((uint64_t ) c198);
    t743 = ((uint64_t ) a2301);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d217 = (t732 - t743);
    b76 = ((t732 < t743));
    d218 = (t731 - t742);
    d219 = (d218 - b76);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d220 = (d217 - t165);
    b77 = ((d217 < t165));
    d221 = (d219 - t164);
    d222 = (d221 - b77);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2306 = ((d219 < t164));
    a2307 = ((d219 == t164));
    a2308 = ((a2307) && (b77));
    i211 = ((a2306) || (a2308));
    t744 = ((i211) ? (d219) : (d222));
    t745 = ((i211) ? (d217) : (d220));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2309 = (2*threadIdx.x);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2310 = (a2309 + 1);
    s239 = (((uint128_t ) T2[a2310]) + ((uint128_t ) t745));
    t746 = ((uint64_t ) s239);
    c199 = (s239 >> 64);
    s240 = (((uint128_t ) T2[a2309]) + ((uint128_t ) t744));
    s241 = (((uint128_t ) s240) + ((uint128_t ) c199));
    t747 = ((uint64_t ) s241);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2311 = ((t164 < t747));
    a2312 = ((t164 == t747));
    a2313 = ((t165 < t746));
    a2314 = ((a2312) && (a2313));
    i212 = ((a2311) || (a2314));
    /* Begin of MPSubDDD 64 */
    d223 = (t746 - t165);
    b78 = ((t746 < t165));
    d224 = (t747 - t164);
    d225 = (d224 - b78);
    /* End of MPSubDDD 64 */
    a2316 = (2*a2309);
    T1[a2316] = ((i212) ? (d225) : (t747));
    a2317 = (a2316 + 1);
    T1[a2317] = ((i212) ? (d223) : (t746));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d226 = (T2[a2310] - t745);
    b79 = ((T2[a2310] < t745));
    d227 = (T2[a2309] - t744);
    d228 = (d227 - b79);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s242 = (((uint128_t ) d226) + ((uint128_t ) t165));
    t748 = ((uint64_t ) s242);
    c200 = (s242 >> 64);
    s243 = (((uint128_t ) d228) + ((uint128_t ) t164));
    s244 = (((uint128_t ) s243) + ((uint128_t ) c200));
    t749 = ((uint64_t ) s244);
    /* MPLessThan 64 */
    a2319 = ((T2[a2309] < t744));
    a2320 = ((T2[a2309] == t744));
    a2321 = ((a2320) && (b79));
    i213 = ((a2319) || (a2321));
    a2322 = (2*a2310);
    T1[a2322] = ((i213) ? (t749) : (d228));
    a2323 = (a2322 + 1);
    T1[a2323] = ((i213) ? (t748) : (d226));
    /* End of MPModSub 64 */
    __syncthreads();
    a2324 = (threadIdx.x + 512);
    a2325 = (a2324 % 512);
    a2326 = (512 + a2325);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2327 = (2*a2326);
    a2328 = (a2327 + 1);
    a2329 = (2*a2324);
    a2330 = (a2329 + 1);
    a2331 = (((uint128_t ) twiddles[a2328])*((uint128_t ) T1[a2330]));
    a2332 = (((uint128_t ) twiddles[a2328])*((uint128_t ) T1[a2329]));
    a2333 = (((uint128_t ) twiddles[a2327])*((uint128_t ) T1[a2330]));
    a2334 = (((uint128_t ) twiddles[a2327])*((uint128_t ) T1[a2329]));
    c201 = (((uint128_t ) a2332) + ((uint128_t ) a2333));
    t750 = (a2331 >> 64);
    c202 = (((uint128_t ) c201) + ((uint128_t ) t750));
    t751 = (c202 >> 64);
    c203 = (((uint128_t ) a2334) + ((uint128_t ) t751));
    t752 = (c203 >> 64);
    t753 = ((uint64_t ) c203);
    t754 = ((uint64_t ) c202);
    t755 = ((uint64_t ) a2331);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p39 = (t754 >> 58);
    p40 = (((t752)&(m4)));
    a2335 = (p40 << 6);
    a2336 = (t753 >> 58);
    t756 = (((a2335)|(a2336)));
    a2337 = (t753 << 6);
    t757 = (((a2337)|(p39)));
    /* End of MPShiftRight3 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2338 = (((uint128_t ) t757)*((uint128_t ) t161));
    a2339 = (((uint128_t ) t757)*((uint128_t ) t160));
    a2340 = (((uint128_t ) t756)*((uint128_t ) t161));
    a2341 = (((uint128_t ) t756)*((uint128_t ) t160));
    c204 = (((uint128_t ) a2339) + ((uint128_t ) a2340));
    t758 = (a2338 >> 64);
    c205 = (((uint128_t ) c204) + ((uint128_t ) t758));
    t759 = (c205 >> 64);
    c206 = (((uint128_t ) a2341) + ((uint128_t ) t759));
    t760 = (c206 >> 64);
    t761 = ((uint64_t ) c206);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t762 = (t760 >> 1);
    a2342 = (t760 << 63);
    a2343 = (t761 >> 1);
    t763 = (((a2342)|(a2343)));
    /* End of MPShiftRight2 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a2344 = (((uint128_t ) t763)*((uint128_t ) t165));
    a2345 = (((uint128_t ) t763)*((uint128_t ) t164));
    a2346 = (((uint128_t ) t762)*((uint128_t ) t165));
    c207 = (((uint128_t ) a2345) + ((uint128_t ) a2346));
    t764 = (a2344 >> 64);
    c208 = (((uint128_t ) c207) + ((uint128_t ) t764));
    t765 = ((uint64_t ) c208);
    t766 = ((uint64_t ) a2344);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d229 = (t755 - t766);
    b80 = ((t755 < t766));
    d230 = (t754 - t765);
    d231 = (d230 - b80);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d232 = (d229 - t165);
    b81 = ((d229 < t165));
    d233 = (d231 - t164);
    d234 = (d233 - b81);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a2349 = ((d231 < t164));
    a2350 = ((d231 == t164));
    a2351 = ((a2350) && (b81));
    i214 = ((a2349) || (a2351));
    t767 = ((i214) ? (d231) : (d234));
    t768 = ((i214) ? (d229) : (d232));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    a2352 = (2*threadIdx.x);
    a2353 = (a1935 + a2352);
    /* Begin of MPModAdd 64 */
    /* MPAddDDD 64 */
    a2354 = (a2352 + 1);
    s245 = (((uint128_t ) T1[a2354]) + ((uint128_t ) t768));
    t769 = ((uint64_t ) s245);
    c209 = (s245 >> 64);
    s246 = (((uint128_t ) T1[a2352]) + ((uint128_t ) t767));
    s247 = (((uint128_t ) s246) + ((uint128_t ) c209));
    t770 = ((uint64_t ) s247);
    /* Begin of MPModDD */
    /* MPLessThan 64 */
    a2355 = ((t164 < t770));
    a2356 = ((t164 == t770));
    a2357 = ((t165 < t769));
    a2358 = ((a2356) && (a2357));
    i215 = ((a2355) || (a2358));
    /* Begin of MPSubDDD 64 */
    d235 = (t769 - t165);
    b82 = ((t769 < t165));
    d236 = (t770 - t164);
    d237 = (d236 - b82);
    /* End of MPSubDDD 64 */
    a2360 = (2*a2353);
    Y[a2360] = ((i215) ? (d237) : (t770));
    a2361 = (a2360 + 1);
    Y[a2361] = ((i215) ? (d235) : (t769));
    /* End of MPModDD */
    /* End of MPModAdd 64 */
    a2362 = (a2353 + 1);
    /* Begin of MPModSub 64 */
    /* Begin of MPSubDDD 64 */
    d238 = (T1[a2354] - t768);
    b83 = ((T1[a2354] < t768));
    d239 = (T1[a2352] - t767);
    d240 = (d239 - b83);
    /* End of MPSubDDD 64 */
    /* MPAddDDD 64 */
    s248 = (((uint128_t ) d238) + ((uint128_t ) t165));
    t771 = ((uint64_t ) s248);
    c210 = (s248 >> 64);
    s249 = (((uint128_t ) d240) + ((uint128_t ) t164));
    s250 = (((uint128_t ) s249) + ((uint128_t ) c210));
    t772 = ((uint64_t ) s250);
    /* MPLessThan 64 */
    a2364 = ((T1[a2352] < t767));
    a2365 = ((T1[a2352] == t767));
    a2366 = ((a2365) && (b83));
    i216 = ((a2364) || (a2366));
    a2367 = (2*a2362);
    Y[a2367] = ((i216) ? (t772) : (d240));
    a2368 = (a2367 + 1);
    Y[a2368] = ((i216) ? (t771) : (d238));
    /* End of MPModSub 64 */
    __syncthreads();
}

void nttmpcuda(uint64_t  *Y, uint64_t  *X, uint64_t modulus[2], uint64_t  *twiddles, uint64_t mu[2]) {
    dim3 b3(512, 1, 1), g1(2, 1, 1);
    ker_code0<<<g1, b3>>>(X, Y, modulus, twiddles, mu);
}

void destroy_nttmpcuda() {
    /* skip */
}
