
/*
 * This code was generated by Spiral 8.5.0, www.spiral.net
 */

#include <stdint.h>

void init_nttmpcuda() {
    /* skip */
}

__global__ void ker_code0(uint64_t  *X, uint64_t  *Y, uint64_t *modulus, uint64_t  *twiddles, uint64_t *mu) {
    int a166, a167, a168, a169, a190, a191, a192, b6, 
            b7, i38;
    uint64_t a174, a175, a176, a177, a178, a183, a184, d10, 
            d11, d12, d7, d8, d9, m4, p3, p4, 
            t38, t39, t42, t43, t52, t53, t54, t55, 
            t56, t57, t58, t59, t60, t61, t62, t63, 
            t64, t65, t66, t67, t68;
    uint128_t a170, a171, a172, a173, a179, a180, a181, a182, 
            a185, a186, a187, c10, c11, c12, c13, c14, 
            c15, c16, c17;
    __shared__ uint64_t T1[8];
    a166 = (1024*blockIdx.x);
    a167 = (a166 + threadIdx.x);
    /* Begin of MPModMul 64 */
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a168 = (2*a167);
    a169 = (a168 + 1);
    a170 = (((uint128_t ) X[a169])*((uint128_t ) twiddles[a169]));
    a171 = (((uint128_t ) X[a169])*((uint128_t ) twiddles[a168]));
    a172 = (((uint128_t ) X[a168])*((uint128_t ) twiddles[a169]));
    a173 = (((uint128_t ) X[a168])*((uint128_t ) twiddles[a168]));
    c10 = (((uint128_t ) a171) + ((uint128_t ) a172));
    t52 = (a170 >> 64);
    c11 = (((uint128_t ) c10) + ((uint128_t ) t52));
    t53 = (c11 >> 64);
    c12 = (((uint128_t ) a173) + ((uint128_t ) t53));
    t54 = (c12 >> 64);
    t55 = ((uint64_t ) c12);
    t56 = ((uint64_t ) c11);
    t57 = ((uint64_t ) a170);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPModDQ */
    /* Begin of MPShiftRight3 */
    p3 = (t56 >> 58);
    a174 = ((uint64_t ) 1);
    a175 = (a174 << 58);
    m4 = (a175 - 1);
    p4 = (((t54)&(m4)));
    a176 = (p4 << 6);
    a177 = (t55 >> 58);
    t58 = (((a176)|(a177)));
    a178 = (t55 << 6);
    t59 = (((a178)|(p3)));
    /* End of MPShiftRight3 */
    t38 = mu[0];
    t39 = mu[1];
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a179 = (((uint128_t ) t59)*((uint128_t ) t39));
    a180 = (((uint128_t ) t59)*((uint128_t ) t38));
    a181 = (((uint128_t ) t58)*((uint128_t ) t39));
    a182 = (((uint128_t ) t58)*((uint128_t ) t38));
    c13 = (((uint128_t ) a180) + ((uint128_t ) a181));
    t60 = (a179 >> 64);
    c14 = (((uint128_t ) c13) + ((uint128_t ) t60));
    t61 = (c14 >> 64);
    c15 = (((uint128_t ) a182) + ((uint128_t ) t61));
    t62 = (c15 >> 64);
    t63 = ((uint64_t ) c15);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPShiftRight2 */
    t64 = (t62 >> 1);
    a183 = (t62 << 63);
    a184 = (t63 >> 1);
    t65 = (((a183)|(a184)));
    /* End of MPShiftRight2 */
    t42 = modulus[0];
    t43 = modulus[1];
    /* Begin of MPMulQDD_Schoolbook_Partial */
    a185 = (((uint128_t ) t65)*((uint128_t ) t43));
    a186 = (((uint128_t ) t65)*((uint128_t ) t42));
    a187 = (((uint128_t ) t64)*((uint128_t ) t43));
    c16 = (((uint128_t ) a186) + ((uint128_t ) a187));
    t66 = (a185 >> 64);
    c17 = (((uint128_t ) c16) + ((uint128_t ) t66));
    t67 = ((uint64_t ) c17);
    t68 = ((uint64_t ) a185);
    /* End of MPMulQDD_Schoolbook_Partial */
    /* Begin of MPSubDDD 64 */
    d7 = (t57 - t68);
    b6 = ((t57 < t68));
    d8 = (t56 - t67);
    d9 = (d8 - b6);
    /* End of MPSubDDD 64 */
    /* Begin of MPSubDDD 64 */
    d10 = (d7 - t43);
    b7 = ((d7 < t43));
    d11 = (d9 - t42);
    d12 = (d11 - b7);
    /* End of MPSubDDD 64 */
    /* MPLessThan 64 */
    a190 = ((d9 < t42));
    a191 = ((d9 == t42));
    a192 = ((a191) && (b7));
    i38 = ((a190) || (a192));
    Y[a168] = ((i38) ? (d9) : (d12));
    Y[a169] = ((i38) ? (d7) : (d10));
    /* End of MPModDQ */
    /* End of MPModMul 64 */
    __syncthreads();
}

void nttmpcuda(uint64_t  *Y, uint64_t  *X, uint64_t modulus[2], uint64_t  *twiddles, uint64_t mu[2]) {
    dim3 b3(1024, 1, 1), g1(2, 1, 1);
    ker_code0<<<g1, b3>>>(X, Y, modulus, twiddles, mu);
}

void destroy_nttmpcuda() {
    /* skip */
}
